### PR TITLE
feat: ollama llama3 api for auto context and embeddings generation

### PR DESCRIPTION
**Pull request by joegoldin**
- Generate embeddings with Ollama via [ollama-python](https://github.com/ollama/ollama-python)
  - Defaults to [`llama3`](https://ollama.com/library/llama3:8b) with dimension length `4096` (can also use `llama2`)
  - Can also use [`all-minilm`](https://ollama.com/library/all-minilm) (sentence-transformers) with dimension length `384` and max context length `256`
  - Can also use [`nomic-embed-text`](https://ollama.com/library/nomic-embed-text) with dimension length `768` and context length `8192`
- Generate llm api responses with Ollama via [ollama-python](https://github.com/ollama/ollama-python)
  - Defaults to [`llama3`](https://ollama.com/library/llama3:8b)
- Added tests for new classes

Requires installation of https://github.com/ollama/ollama

resolves https://github.com/SuperpoweredAI/spRAG/issues/5
resolves https://github.com/SuperpoweredAI/spRAG/issues/6

### CODE REVIEW

**Comment by zmccormick7** [comment]
I'm getting the following error when trying to run the new tests for this PR: `httpx.ConnectError: [Errno 61] Connection refused`. This is coming from the `ollama.pull(model)` line. Are these tests passing for you? If so, could there be some additional setup required, beyond just `pip install ollama`?

**Comment by dr-kd** [comment]
To run the tests it's assuming a locally running ollama with the lama3 model available, so install ollama via https://ollama.com/download and then `ollama pull llama3`.  After that `pytest tests/unit/test_llm.py` is working for me

**Comment by joegoldin** [comment]
> If so, could there be some additional setup required

Yep, apologies for not making it clearer. This does add an external dependency on Ollama running on your machine. It is cross platform and is one of the few that supports Windows and AMD rocm, so it's really nice with my AMD 7900XTX.

**Comment by dr-kd** [comment]
suggesting this patch in lieu of an ollama setup script: 

```
diff --git a/sprag/llm.py b/sprag/llm.py
index 808cc4f..9bbd774 100644
--- a/sprag/llm.py
+++ b/sprag/llm.py
@@ -102 +102 @@ class OllamaAPI(LLM):
-        self, model: str = "llama3", temperature: float = 0.2, max_tokens: int = 1000, client: ollama.Client = None
+        self, model: str = "llama3", temperature: float = 0.2, max_tokens: int = 1000, client: ollama.Client = None, pull: bool = False
@@ -108 +108,2 @@ class OllamaAPI(LLM):
-        ollama.pull(self.model)
+        if pull:
+            ollama.pull(self.model)
```

**Review by NickGator1 — APPROVED** [review]

**Pull request merged**
